### ISSUE TITLE
popup

### ISSUE THREAD

**Issue by waste-of-space** [BoringCode/TranslateThis#12]
The popup asking me if I would like to submit a better translation keeps popping up over the words that I am trying to read.
Could you add an option to turn this annoying 'feature' off please?

Thank you

**Comment by BoringCode** [comment]
This "feature" is a part of Google Translate. I have no control over how Google styles their site.

**Comment by waste-of-space** [comment]
Thank you anyway for answering me.
I will write to Google translate now.
