### ISSUE TITLE
No icon in toolbar

### ISSUE THREAD

**Issue by kitaro64** [BoringCode/TranslateThis#13]
"Convenient toolbar button to translate the entire page." is an issue for me...I used to see the icon in my toolbar and recently noticed that it was gone...I tried uninstalling and re-installing Tranlate This but till no icon...

I have tried resetting my Firefox back to default and I still do not get the Translate This icon to appear.

I am using Firefox 41.0.1 on a Windows 7 system (x86)

Any advice/feedback you could provide would be appreciated.

Thank you for your time and effort.

**Comment by BoringCode** [comment]
What version of Translate This are you using?

**Comment by kitaro64** [comment]
3.0.2.1-signed

**Comment by BoringCode** [comment]
That version does not support the latest version of Firefox. 

Mozilla still hasn't reviewed the new version that fixes these problems, but in the meantime you can install the [beta version](https://github.com/BoringCode/TranslateThis/releases/tag/v3.5.0)

**Comment by kitaro64** [comment]
The beta version works like a charm...Thank you for your help, time and effort...
