### ISSUE TITLE
Please add support for Multiprocess

### ISSUE THREAD

**Issue by Red-Squid** [BoringCode/TranslateThis#16]
Firefox is evolving, please adapt this add-on to keep it valid. Thanks!

https://wiki.mozilla.org/Electrolysis

**Comment by BoringCode** [comment]
Have you personally tested it with the dev builds? 

I haven't done that yet, but my understanding was that if I used standard Addon SDK APIs (which I have) that the addon should support multi-process Firefox out of the box.

**Comment by Red-Squid** [comment]
don't know specifically, it's flagged as not compatible by Addon
Compatibility Reporter... a tool that's suggested for people who want to
see if there add-ons are compatible with e10s/multiprocess in the new FF.

FF will default to e10s = off if add-ons aren't compatible; unless it's
forced on, which can break things.

Should probably be rewritten in WebExtension format anyway, makes it pretty
much plug 'n' play on other browsers too. ; )

On Tue, Sep 13, 2016 at 6:38 PM, Bradley Rosenfeld <notifications@github.com

**Comment by rmbleeker** [comment]
I can confirm that this add-on is indeed not compatible with multiprocess on Firefox 49
https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox

**Comment by BoringCode** [comment]
Thanks for confirming. Do you have any more information on what is failing? I looked over the rules of thumb for compatibility and Translate This doesn't seem to fail any of them. 

I haven't had much time to focus on my Firefox addon projects as of late, but I'll certainly try to get this fixed before e10s drops. 

I do accept pull requests :)

**Comment by BoringCode** [comment]
Apparently I misread the docs and incorrectly set the multiprocess in package.json. I tested it in Firefox Nightly and multiprocess appears to be working fine. 

Version 3.5.1 has been uploaded to the AMO for review, hopefully it will be pushed to users soon.
